#!/usr/bin/env bash

set -e

builddir=_doc_build

rm -rf "$builddir"
meson setup "$builddir"
ninja -C "$builddir"
rsync --delete -avz "$builddir/html/" freedesktop.org:/srv/www.freedesktop.org/www/software/libevdev/doc/latest
rm -rf "$builddir"
